### ISSUE TITLE
First line of error stack is not presented

### ISSUE THREAD

**Issue by mrbar42** [DonJayamanne/typescript-notebook#51]
For some reason the first line of any error thrown in a cell is trimmed.
i assume there is some sort of cleanup going on to remove internal frames, but the first line with the message should always be shown.

to reproduce simply throw an error in a code cell in a notebook (see pic).

![image](https://user-images.githubusercontent.com/12373774/154830976-4a4260a8-5bda-4215-8a1c-ab25981e802d.png)

<details>
<summary>Version & OS Info</summary>

Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:58.347Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0

</details>

**Comment by DonJayamanne** [comment]
Fixed.

**Comment by JoshWillik** [comment]
I don't think it's fixed, I'm still seeing this today
![image](https://user-images.githubusercontent.com/2429492/233810450-a7bb0ebd-aea0-4a30-96ca-946bae613c1a.png)

**Comment by idpsycho** [comment]
@DonJayamanne  still doesnt work, can we reopen this?
